from __future__ import annotations

from typing import Any

SUPPORTED_LANGUAGES = ("en", "es", "gl")
DEFAULT_LANGUAGE = "en"

LANGUAGE_OPTIONS = (
    {"key": "en", "label": "English"},
    {"key": "es", "label": "Español"},
    {"key": "gl", "label": "Galego"},
)

_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "nav_home": "Home",
        "nav_collection": "Collection",
        "nav_bag": "Bag",
        "nav_shop": "Shop",
        "nav_settings": "Settings",
        "refresh": "Refresh",
        "loading": "Loading usage and limits…",
        "updated": "Updated",
        "updated_warnings": "Updated with warnings",
        "status_stale": "Data is stale · refreshing…",
        "status_updating": "Updating…",
        "status_failed": "Update failed · retry scheduled",
        "limit_5_hour": "5-hour",
        "limit_weekly": "Weekly",
        "home_description": "Local usage, limits, and companion progress",
        "current_companion": "CURRENT COMPANION",
        "pokemon_egg": "Pokémon Egg",
        "waiting_to_hatch": "Waiting to hatch{tier}",
        "hatch_hint": "Hatch the egg to discover its evolution line",
        "current_next": "Current: {current}  →  Next: {next}",
        "current_final": "Current: {current} · final evolution",
        "tokens_today": "Today",
        "estimated_cost": "Est. cost",
        "this_week": "This week",
        "wallet": "Wallet",
        "providers": "Providers",
        "official_limits": "Official limits",
        "no_provider_data": "No provider usage data available",
        "no_limit_data": "No official limit data available",
        "today_short": "today",
        "week_short": "week",
        "month_short": "month",
        "unavailable": "unavailable",
        "reset_unknown": "reset unknown",
        "resets": "resets",
        "forecast": "forecast",
        "forecast_full": "full {when}",
        "forecast_safe": "safe until reset",
        "forecast_not_enough": "not enough data yet",
        "forecast_collecting": "collecting usage data",
        "forecast_reset_unknown": "reset time unavailable",
        "forecast_duration_unknown": "window duration unavailable",
        "forecast_already_reset": "window already reset",
        "resets_available": "{count} resets available",
        "reset_available": "1 reset available",
        "first_expires": "first expires",
        "expires": "expires",
        "expiry_unknown": "expiry unknown",
        "reserve_unavailable": "unavailable",
        "collection_description": "Your Pokédex and complete catch history",
        "pokedex": "Pokédex",
        "catch_log": "Catch log",
        "collection_view": "Collection view",
        "dex_open": "View {name}",
        "dex_back": "Back to Pokédex",
        "dex_position": "{position} of {count}",
        "fully_evolved": "Fully evolved",
        "have_only_stage": "Only stage {stage} of {total}",
        "refresh_help": "How often local usage and official limits are checked.",
        "language_tooltip": "Changes the app language and Pokémon names when available.",
        "start_windows_help": "Start PokeTokenBar in the tray when you sign in. The window stays closed; the desktop pet appears only when enabled.",
        "show_floating_help": "Keep your chosen Pokémon visible on the desktop.",
        "pet_size_help": "Adjust the size of the floating Pokémon.",
        "usage_bubbles_help": "Show limit warnings above the desktop Pokémon.",
        "quota_help": "Show each limit as used or remaining, including notifications.",
        "reset_format_help": "Show reset times as a countdown or a calendar date.",
        "forecast_help": "Estimate when each timed limit may be exhausted.",
        "limit_notifications_help": "Notify when official limit thresholds are reached.",
        "pokemon_notifications_help": "Notify when your companion hatches or evolves.",
        "warning_help": "Notify when this percentage of a limit has been used.",
        "critical_help": "Notify at this higher used-percentage threshold.",
        "theme_help": "Follow Windows or choose a light or dark appearance.",
        "tray_today_help": "Include today's local token count in the tray tooltip.",
        "tray_cost_help": "Include today's estimated cost in the tray tooltip.",
        "tray_limit_help": "Include the most relevant official limit in the tray and pet tooltips.",
        "backup_help": "Export or import your companion progress and settings.",

        "page": "Page {page} / {count}",
        "filter_by": "Filter by {label}",
        "all": "All",
        "species_count": "{count} species",
        "previous": "← Previous",
        "next": "Next →",
        "empty_pokedex": "Hatch your first egg to start the Pokédex.",
        "empty_catches": "No catches yet.",
        "raising": "RAISING",
        "obtained": "Obtained",
        "current": "Current",
        "future": "Future",
        "view_normal": "Show normal {name}",
        "view_shiny": "Show shiny {name}",
        "bag_description": "Items available for your companion",
        "available_count": "{count} available",
        "use_on_companion": "Use on companion",
        "change_nature": "Change nature",
        "charm_active": "Active · improves the odds of future shiny Pokémon",
        "charm_inactive": "Not active",
        "shop_description": "Spend only tokens observed since installation",
        "buy": "Buy {title}: {price}",
        "already_active": "Already active",
        "tokens": "tokens",
        "settings_description": "Customize monitoring, the desktop pet, and appearance",
        "general": "General",
        "refresh_interval": "Refresh interval",
        "minutes": "{count} min",
        "language": "Language",
        "language_help": "Also controls Pokémon names when a translation is available.",
        "start_windows": "Start automatically with Windows",
        "desktop_representative": "Desktop representative",
        "representative_help": "Controls the tray icon and floating desktop pet.",
        "set_representative": "Set as desktop companion",
        "representative_selected": "Desktop companion selected",
        "following_current": "Following current companion",
        "follow_companion": "Follow active companion",
        "desktop_pet": "Desktop pet",
        "show_floating": "Show floating companion",
        "size": "Size",
        "pet_size": "Pet size",
        "usage_bubbles": "Usage and reset bubbles",
        "limits_alerts": "Limits and alerts",
        "show_quota": "Show quota",
        "used": "Used",
        "remaining": "Remaining",
        "quota_percentage": "Quota percentage",
        "reset_format": "Reset format",
        "time": "Time remaining",
        "date": "Date",
        "forecast_timed": "Forecast every timed limit",
        "limit_notifications": "Limit notifications",
        "pokemon_notifications": "Pokémon event notifications",
        "warning": "Warning",
        "critical": "Critical",
        "warning_threshold": "Warning threshold",
        "critical_threshold": "Critical threshold",
        "appearance_data": "Appearance and data",
        "theme": "Theme",
        "theme_system": "System",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "interface_theme": "Interface theme",
        "tray_today": "Today's tokens in tray",
        "tray_cost": "Estimated cost in tray",
        "tray_limit": "Primary limit in tray",
        "export_backup": "Export backup…",
        "import_backup": "Import backup…",
        "rare_candy": "Rare Candy",
        "rare_candy_description": "Progress boost",
        "mint": "Mint",
        "mint_description": "Change nature",
        "shiny_charm": "Shiny Charm",
        "shiny_charm_description": "Better shiny odds",
        "normal_egg": "Normal Egg",
        "normal_egg_description": "A fresh companion",
        "uncommon_egg": "Uncommon Egg",
        "uncommon_egg_description": "Uncommon or better",
        "rare_egg": "Rare Egg",
        "rare_egg_description": "Rare or better",
        "common": "Common",
        "uncommon": "Uncommon",
        "rare": "Rare",
        "legendary": "Legendary",
        "stage": "stage",
        "nature": "nature",
        "startup_error": "Windows could not change the startup setting.",
    },
    "es": {
        "nav_home": "Inicio",
        "nav_collection": "Colección",
        "nav_bag": "Bolsa",
        "nav_shop": "Tienda",
        "nav_settings": "Ajustes",
        "refresh": "Actualizar",
        "loading": "Cargando uso y límites…",
        "updated": "Actualizado",
        "updated_warnings": "Actualizado con avisos",
        "status_stale": "Los datos están desactualizados · actualizando…",
        "status_updating": "Actualizando…",
        "status_failed": "Falló la actualización · reintento programado",
        "limit_5_hour": "5 horas",
        "limit_weekly": "Semanal",
        "home_description": "Uso local, límites y progreso del compañero",
        "current_companion": "COMPAÑERO ACTUAL",
        "pokemon_egg": "Huevo Pokémon",
        "waiting_to_hatch": "Esperando para eclosionar{tier}",
        "hatch_hint": "Eclosiona el huevo para descubrir su línea evolutiva",
        "current_next": "Actual: {current}  →  Siguiente: {next}",
        "current_final": "Actual: {current} · evolución final",
        "tokens_today": "Hoy",
        "estimated_cost": "Coste estimado",
        "this_week": "Esta semana",
        "wallet": "Monedero",
        "providers": "Proveedores",
        "official_limits": "Límites oficiales",
        "no_provider_data": "No hay datos de uso de proveedores",
        "no_limit_data": "No hay datos de límites oficiales",
        "today_short": "hoy",
        "week_short": "semana",
        "month_short": "mes",
        "unavailable": "no disponible",
        "reset_unknown": "reinicio desconocido",
        "resets": "reinicia",
        "forecast": "previsión",
        "forecast_full": "se agotará {when}",
        "forecast_safe": "no se agotará antes del reinicio",
        "forecast_not_enough": "aún no hay suficientes datos",
        "forecast_collecting": "recopilando datos de uso",
        "forecast_reset_unknown": "hora de reinicio no disponible",
        "forecast_duration_unknown": "duración de ventana no disponible",
        "forecast_already_reset": "la ventana ya se reinició",
        "resets_available": "{count} reinicios disponibles",
        "reset_available": "1 reinicio disponible",
        "first_expires": "el primero caduca",
        "expires": "caduca",
        "expiry_unknown": "caducidad desconocida",
        "reserve_unavailable": "no disponible",
        "collection_description": "Tu Pokédex y el historial completo de capturas",
        "pokedex": "Pokédex",
        "catch_log": "Capturas",
        "collection_view": "Vista de colección",
        "dex_open": "Ver {name}",
        "dex_back": "Volver a la Pokédex",
        "dex_position": "{position} de {count}",
        "fully_evolved": "Completamente evolucionado",
        "have_only_stage": "Solo fase {stage} de {total}",
        "refresh_help": "Cada cuánto se comprueban el uso local y los límites oficiales.",
        "language_tooltip": "Cambia el idioma y los nombres Pokémon disponibles.",
        "start_windows_help": "Inicia PokeTokenBar en la bandeja al entrar en Windows. La ventana queda cerrada; la mascota aparece solo si está activada.",
        "show_floating_help": "Muestra el Pokémon elegido en el escritorio.",
        "pet_size_help": "Ajusta el tamaño del Pokémon flotante.",
        "usage_bubbles_help": "Muestra avisos de límites sobre la mascota.",
        "quota_help": "Muestra los límites usados o restantes, también en los avisos.",
        "reset_format_help": "Muestra el reinicio como cuenta atrás o fecha.",
        "forecast_help": "Estima cuándo se agotará cada límite temporal.",
        "limit_notifications_help": "Avisa al alcanzar los umbrales de límites oficiales.",
        "pokemon_notifications_help": "Avisa cuando el compañero nace o evoluciona.",
        "warning_help": "Avisa al consumir este porcentaje de un límite.",
        "critical_help": "Avisa al alcanzar este umbral superior de consumo.",
        "theme_help": "Sigue Windows o elige un aspecto claro u oscuro.",
        "tray_today_help": "Incluye los tokens locales de hoy en la bandeja.",
        "tray_cost_help": "Incluye el coste estimado de hoy en la bandeja.",
        "tray_limit_help": "Incluye el límite oficial más relevante en la bandeja y la mascota.",
        "backup_help": "Exporta o importa el progreso y los ajustes.",

        "page": "Página {page} / {count}",
        "filter_by": "Filtrar por {label}",
        "all": "Todas",
        "species_count": "{count} especies",
        "previous": "← Anterior",
        "next": "Siguiente →",
        "empty_pokedex": "Eclosiona tu primer huevo para comenzar la Pokédex.",
        "empty_catches": "Todavía no hay capturas.",
        "raising": "EN CRIANZA",
        "obtained": "Obtenida",
        "current": "Actual",
        "future": "Futura",
        "view_normal": "Ver normal de {name}",
        "view_shiny": "Ver shiny de {name}",
        "bag_description": "Objetos disponibles para tu compañero",
        "available_count": "{count} disponibles",
        "use_on_companion": "Usar en el compañero",
        "change_nature": "Cambiar naturaleza",
        "charm_active": "Activo · mejora la probabilidad de futuros shiny",
        "charm_inactive": "No está activo",
        "shop_description": "Gasta solo los tokens observados desde la instalación",
        "buy": "Comprar {title}: {price}",
        "already_active": "Ya está activo",
        "tokens": "tokens",
        "settings_description": "Personaliza la supervisión, la mascota y el aspecto",
        "general": "General",
        "refresh_interval": "Intervalo de actualización",
        "minutes": "{count} min",
        "language": "Idioma",
        "language_help": "También controla los nombres Pokémon cuando hay traducción.",
        "start_windows": "Iniciar automáticamente con Windows",
        "desktop_representative": "Representante de escritorio",
        "representative_help": "Controla el icono de la bandeja y la mascota flotante.",
        "set_representative": "Usar como compañero de escritorio",
        "representative_selected": "Compañero de escritorio seleccionado",
        "following_current": "Siguiendo al compañero actual",
        "follow_companion": "Seguir al compañero actual",
        "desktop_pet": "Mascota de escritorio",
        "show_floating": "Mostrar compañero flotante",
        "size": "Tamaño",
        "pet_size": "Tamaño de mascota",
        "usage_bubbles": "Burbujas de uso y reinicios",
        "limits_alerts": "Límites y avisos",
        "show_quota": "Mostrar cuota",
        "used": "Usada",
        "remaining": "Restante",
        "quota_percentage": "Porcentaje de cuota",
        "reset_format": "Formato de reinicios",
        "time": "Tiempo restante",
        "date": "Fecha",
        "forecast_timed": "Previsión para todos los límites temporales",
        "limit_notifications": "Notificaciones de límites",
        "pokemon_notifications": "Notificaciones de eventos Pokémon",
        "warning": "Aviso",
        "critical": "Crítico",
        "warning_threshold": "Umbral de aviso",
        "critical_threshold": "Umbral crítico",
        "appearance_data": "Aspecto y datos",
        "theme": "Tema",
        "theme_system": "Sistema",
        "theme_light": "Claro",
        "theme_dark": "Oscuro",
        "interface_theme": "Tema de la interfaz",
        "tray_today": "Tokens de hoy en la bandeja",
        "tray_cost": "Coste estimado en la bandeja",
        "tray_limit": "Límite principal en la bandeja",
        "export_backup": "Exportar copia…",
        "import_backup": "Importar copia…",
        "rare_candy": "Caramelo Raro",
        "rare_candy_description": "Aumenta el progreso",
        "mint": "Menta",
        "mint_description": "Cambia la naturaleza",
        "shiny_charm": "Amuleto Iris",
        "shiny_charm_description": "Mejora la probabilidad shiny",
        "normal_egg": "Huevo normal",
        "normal_egg_description": "Un nuevo compañero",
        "uncommon_egg": "Huevo poco común",
        "uncommon_egg_description": "Poco común o mejor",
        "rare_egg": "Huevo raro",
        "rare_egg_description": "Raro o mejor",
        "common": "Común",
        "uncommon": "Poco común",
        "rare": "Raro",
        "legendary": "Legendario",
        "stage": "fase",
        "nature": "naturaleza",
        "startup_error": "Windows no pudo cambiar el inicio automático.",
    },
    "gl": {
        "nav_home": "Inicio",
        "nav_collection": "Colección",
        "nav_bag": "Bolsa",
        "nav_shop": "Tenda",
        "nav_settings": "Axustes",
        "refresh": "Actualizar",
        "loading": "Cargando uso e límites…",
        "updated": "Actualizado",
        "updated_warnings": "Actualizado con avisos",
        "status_stale": "Os datos están desactualizados · actualizando…",
        "status_updating": "Actualizando…",
        "status_failed": "Fallou a actualización · reintento programado",
        "limit_5_hour": "5 horas",
        "limit_weekly": "Semanal",
        "home_description": "Uso local, límites e progreso do compañeiro",
        "current_companion": "COMPAÑEIRO ACTUAL",
        "pokemon_egg": "Ovo Pokémon",
        "waiting_to_hatch": "Agardando para eclosionar{tier}",
        "hatch_hint": "Eclosiona o ovo para descubrir a súa liña evolutiva",
        "current_next": "Actual: {current}  →  Seguinte: {next}",
        "current_final": "Actual: {current} · evolución final",
        "tokens_today": "Hoxe",
        "estimated_cost": "Custo estimado",
        "this_week": "Esta semana",
        "wallet": "Moedeiro",
        "providers": "Provedores",
        "official_limits": "Límites oficiais",
        "no_provider_data": "Non hai datos de uso de provedores",
        "no_limit_data": "Non hai datos de límites oficiais",
        "today_short": "hoxe",
        "week_short": "semana",
        "month_short": "mes",
        "unavailable": "non dispoñible",
        "reset_unknown": "reinicio descoñecido",
        "resets": "reinicia",
        "forecast": "previsión",
        "forecast_full": "esgotarase {when}",
        "forecast_safe": "non se esgotará antes do reinicio",
        "forecast_not_enough": "aínda non hai datos suficientes",
        "forecast_collecting": "recollendo datos de uso",
        "forecast_reset_unknown": "hora de reinicio non dispoñible",
        "forecast_duration_unknown": "duración da xanela non dispoñible",
        "forecast_already_reset": "a xanela xa se reiniciou",
        "resets_available": "{count} reinicios dispoñibles",
        "reset_available": "1 reinicio dispoñible",
        "first_expires": "o primeiro caduca",
        "expires": "caduca",
        "expiry_unknown": "caducidade descoñecida",
        "reserve_unavailable": "non dispoñible",
        "collection_description": "A túa Pokédex e o historial completo de capturas",
        "pokedex": "Pokédex",
        "catch_log": "Capturas",
        "collection_view": "Vista da colección",
        "dex_open": "Ver {name}",
        "dex_back": "Volver á Pokédex",
        "dex_position": "{position} de {count}",
        "fully_evolved": "Completamente evolucionado",
        "have_only_stage": "Só fase {stage} de {total}",
        "refresh_help": "Cada canto se comproban o uso local e os límites oficiais.",
        "language_tooltip": "Cambia o idioma e os nomes Pokémon dispoñibles.",
        "start_windows_help": "Inicia PokeTokenBar na bandexa ao entrar en Windows. A ventá queda pechada; a mascota aparece só se está activada.",
        "show_floating_help": "Amosa o Pokémon escollido no escritorio.",
        "pet_size_help": "Axusta o tamaño do Pokémon flotante.",
        "usage_bubbles_help": "Amosa avisos de límites sobre a mascota.",
        "quota_help": "Amosa os límites usados ou restantes, tamén nos avisos.",
        "reset_format_help": "Amosa o reinicio como conta atrás ou data.",
        "forecast_help": "Estima cando se esgotará cada límite temporal.",
        "limit_notifications_help": "Avisa ao chegar aos limiares dos límites oficiais.",
        "pokemon_notifications_help": "Avisa cando o compañeiro nace ou evoluciona.",
        "warning_help": "Avisa ao consumir esta porcentaxe dun límite.",
        "critical_help": "Avisa ao chegar a este limiar superior de consumo.",
        "theme_help": "Segue Windows ou escolle un aspecto claro ou escuro.",
        "tray_today_help": "Inclúe os tokens locais de hoxe na bandexa.",
        "tray_cost_help": "Inclúe o custo estimado de hoxe na bandexa.",
        "tray_limit_help": "Inclúe o límite oficial máis relevante na bandexa e na mascota.",
        "backup_help": "Exporta ou importa o progreso e os axustes.",

        "page": "Páxina {page} / {count}",
        "filter_by": "Filtrar por {label}",
        "all": "Todas",
        "species_count": "{count} especies",
        "previous": "← Anterior",
        "next": "Seguinte →",
        "empty_pokedex": "Eclosiona o teu primeiro ovo para comezar a Pokédex.",
        "empty_catches": "Aínda non hai capturas.",
        "raising": "EN CRIANZA",
        "obtained": "Obtida",
        "current": "Actual",
        "future": "Futura",
        "view_normal": "Ver normal de {name}",
        "view_shiny": "Ver shiny de {name}",
        "bag_description": "Obxectos dispoñibles para o teu compañeiro",
        "available_count": "{count} dispoñibles",
        "use_on_companion": "Usar no compañeiro",
        "change_nature": "Cambiar natureza",
        "charm_active": "Activo · mellora a probabilidade de futuros shiny",
        "charm_inactive": "Non está activo",
        "shop_description": "Gasta só os tokens observados desde a instalación",
        "buy": "Mercar {title}: {price}",
        "already_active": "Xa está activo",
        "tokens": "tokens",
        "settings_description": "Personaliza a supervisión, a mascota e o aspecto",
        "general": "Xeral",
        "refresh_interval": "Intervalo de actualización",
        "minutes": "{count} min",
        "language": "Idioma",
        "language_help": "Tamén controla os nomes Pokémon cando hai tradución.",
        "start_windows": "Iniciar automaticamente con Windows",
        "desktop_representative": "Representante de escritorio",
        "representative_help": "Controla a icona da bandexa e a mascota flotante.",
        "set_representative": "Usar como compañeiro de escritorio",
        "representative_selected": "Compañeiro de escritorio seleccionado",
        "following_current": "Seguindo o compañeiro actual",
        "follow_companion": "Seguir o compañeiro actual",
        "desktop_pet": "Mascota de escritorio",
        "show_floating": "Mostrar compañeiro flotante",
        "size": "Tamaño",
        "pet_size": "Tamaño da mascota",
        "usage_bubbles": "Bocadillos de uso e reinicios",
        "limits_alerts": "Límites e avisos",
        "show_quota": "Mostrar cota",
        "used": "Usada",
        "remaining": "Restante",
        "quota_percentage": "Porcentaxe da cota",
        "reset_format": "Formato dos reinicios",
        "time": "Tempo restante",
        "date": "Data",
        "forecast_timed": "Previsión para todos os límites temporais",
        "limit_notifications": "Notificacións de límites",
        "pokemon_notifications": "Notificacións de eventos Pokémon",
        "warning": "Aviso",
        "critical": "Crítico",
        "warning_threshold": "Limiar de aviso",
        "critical_threshold": "Limiar crítico",
        "appearance_data": "Aspecto e datos",
        "theme": "Tema",
        "theme_system": "Sistema",
        "theme_light": "Claro",
        "theme_dark": "Escuro",
        "interface_theme": "Tema da interface",
        "tray_today": "Tokens de hoxe na bandexa",
        "tray_cost": "Custo estimado na bandexa",
        "tray_limit": "Límite principal na bandexa",
        "export_backup": "Exportar copia…",
        "import_backup": "Importar copia…",
        "rare_candy": "Caramelo Raro",
        "rare_candy_description": "Aumenta o progreso",
        "mint": "Menta",
        "mint_description": "Cambia a natureza",
        "shiny_charm": "Amuleto Iris",
        "shiny_charm_description": "Mellora a probabilidade shiny",
        "normal_egg": "Ovo normal",
        "normal_egg_description": "Un novo compañeiro",
        "uncommon_egg": "Ovo pouco común",
        "uncommon_egg_description": "Pouco común ou mellor",
        "rare_egg": "Ovo raro",
        "rare_egg_description": "Raro ou mellor",
        "common": "Común",
        "uncommon": "Pouco común",
        "rare": "Raro",
        "legendary": "Lendario",
        "stage": "fase",
        "nature": "natureza",
        "startup_error": "Windows non puido cambiar o inicio automático.",
    },
}


# Native Qt surfaces share this vocabulary with the QML interface.
_NATIVE_STRINGS = {
    "en": {"menu_open": "Open PokeTokenBar", "menu_pet": "Show desktop pet", "menu_quit": "Quit", "catch_owned": "You have this", "catch_previous": "Previous form", "catch_future": "Not owned"},
    "es": {"menu_open": "Abrir PokeTokenBar", "menu_pet": "Mostrar mascota de escritorio", "menu_quit": "Salir", "catch_owned": "Lo tienes", "catch_previous": "Forma anterior", "catch_future": "No obtenido"},
    "gl": {"menu_open": "Abrir PokeTokenBar", "menu_pet": "Amosar mascota no escritorio", "menu_quit": "Saír", "catch_owned": "Xa o tes", "catch_previous": "Forma anterior", "catch_future": "Sen obter"},
}
for _language, _entries in _NATIVE_STRINGS.items():
    _STRINGS[_language].update(_entries)

_SURFACE_PHRASES = {
    "es": {
        "Critical limit": "Límite crítico", "Limit warning": "Aviso de límite",
        "Full reset expires soon": "El reinicio completo caduca pronto",
        "Full reset reminder": "Recordatorio de reinicio completo",
        "full reset expiry is unknown": "reinicio completo con caducidad desconocida",
        "full reset": "reinicio completo", "tokens today": "tokens hoy",
        "estimated cost today": "coste estimado hoy", "today": "hoy",
        "5-hour": "5 horas", "Weekly": "Semanal", "remaining": "restante",
        "used": "usado", "left": "restante", "expires": "caduca",
        "Warning": "Aviso", "Critical": "Crítico", "in": "en", "now": "ahora", "egg": "huevo", "Lv": "Nv",
    },
    "gl": {
        "Critical limit": "Límite crítico", "Limit warning": "Aviso de límite",
        "Full reset expires soon": "O reinicio completo caduca axiña",
        "Full reset reminder": "Lembranza de reinicio completo",
        "full reset expiry is unknown": "reinicio completo con caducidade descoñecida",
        "full reset": "reinicio completo", "tokens today": "tokens hoxe",
        "estimated cost today": "custo estimado hoxe", "today": "hoxe",
        "5-hour": "5 horas", "Weekly": "Semanal", "remaining": "restante",
        "used": "usado", "left": "restante", "expires": "caduca",
        "Warning": "Aviso", "Critical": "Crítico", "in": "en", "now": "agora", "egg": "ovo", "Lv": "Nv",
    },
}


def normalize_language(language: Any) -> str:
    candidate = str(language or "").strip().lower()
    return candidate if candidate in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def ui_strings(language: Any) -> dict[str, str]:
    normalized = normalize_language(language)
    return dict(_STRINGS[normalized])


def text(language: Any, key: str, **values: Any) -> str:
    normalized = normalize_language(language)
    template = _STRINGS[normalized].get(key, _STRINGS[DEFAULT_LANGUAGE].get(key, key))
    return template.format(**values)

def localize_surface(value: str, language: Any = "en") -> str:
    """Translate fixed formatter vocabulary while preserving names and values."""
    import re
    phrases = _SURFACE_PHRASES.get(normalize_language(language))
    if not phrases:
        return value
    pattern = r"(?<!\w)(" + "|".join(
        re.escape(key) for key in sorted(phrases, key=len, reverse=True)
    ) + r")(?!\w)"
    return re.sub(pattern, lambda match: phrases[match.group(0)], value)

